server:
  port: 8080

spring:
  datasource:
    druid:
      url: jdbc:mysql://111.229.57.140:3306/springboot-bbs?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&allowMultiQueries=true
      username: root
      password: denglei520
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  redis:
    database: 0
    timeout: 1000
    password: denglei
    cluster:
      nodes: 111.229.57.140:8001,111.229.57.140:8002,111.229.57.140:8003,111.229.179.233:8004,111.229.179.233:8005,111.229.179.233:8006
      lettuce:
      pool:
        max-idle: 50
        min-idle: 10
        max-active: 100
        max-wait: -1

mybatis:
  type-aliases-package: cn.denglei.bbs.entity
  mapper-locations: classpath:mapper/*.xml